### ISSUE TITLE
can it be used to show a simple text message with custom colors?

### ISSUE THREAD

**Issue by ivanbalashov239** [DidgeridooMH/MercuryOS#8]
Hi, So what i want: simple os/program running on bare metal, grub boots it and it shows simple text message, nothing else. Could you tell how i could do it with your project?

**Comment by DidgeridooMH** [comment]
If you go into the kernel.c file, you'll see it sets up all the bare bones stuff. After the mercury os title is printed you can delete all the test code 
"asm("int 0x32");

  while(1) {
    shell_prompt();
  }"

Then you can clear the screen with vga_clear_screen(), as well as change the text color with vga_set_color. From there print whatever you want before the kmain function ends.

**Comment by ivanbalashov239** [comment]
@DidgeridooMH thanks, will see
